
spring:
  application:
    name: eurekaclient
  profiles: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
---
spring:
     profiles: 8001
     application:
       name: eurekaclient
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/